### ISSUE TITLE
Cannot build and start demo sample 

### ISSUE THREAD

**Issue by budarin** [GoogleChromeLabs/sw-precache#273]
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/rev-manifest.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/.../sw-precache/app-shell-demo/src/server.js:56:19)
    at Module._compile (module.js:571:32)
    at loader (/...sw-precache/app-shell-demo/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/.../sw-precache/app-shell-demo/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by devnook** [comment]
I think you might be trying to use "npm start" here. Maybe try gulp instead:

```
npm install -g gulp
gulp
```
